CREATE TABLE aoai.token_count_usage (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY(SEQUENCE NAME token_count_usage_id_seq START WITH 1 INCREMENT BY 50) PRIMARY KEY,
                                        product_id VARCHAR NOT NULL,
                                        endpoint VARCHAR NOT NULL,
                                        model VARCHAR NOT NULL,
                                        event_time TIMESTAMP NOT NULL,
                                        prompt_tokens INT,
                                        completion_tokens INT,
                                        total_tokens INT
);